name: Run Tests, Lint, and Build

on: [push, pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies for netCDF4
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libnetcdf-dev pkg-config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4
          pip install --no-binary :all: --force-reinstall netCDF4 scipy
          pip install -e .
      
      - name: Lint with Ruff
        run: ruff check .

      - name: Run tests
        run: pytest

      - name: Build the package
        run: python -m build

      - name: Check built distribution with Twine
        run: twine check dist/*
